### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by inushima** [aikms-maker/BMI-Calculator-iOS13#1]
https://github.com/aikms-maker/BMI-Calculator-iOS13/blob/master/BMI%20Calculator/CalculateViewController.swift#L22
https://github.com/aikms-maker/BMI-Calculator-iOS13/blob/master/BMI%20Calculator/CalculateViewController.swift#L39

getBmiValue()メソッドが呼び出されていますが、戻り値が使用されていないため、Xcodeで警告が出ています。
![スクリーンショット 2023-01-23 17 59 03](https://user-images.githubusercontent.com/8144028/214002066-02cf9b61-28d3-4c76-a4dc-bdb37d1d257b.jpg)

呼び出し自体が不要な場合は削除お願いします。

もし呼び出しが必要で、意図的に戻り値を使用しない場合は、以下のように書くと警告が消えます。

```
_ = calculatorBrain.getBmiValue()
```

**Comment by inushima** [comment]
[imo]
https://github.com/aikms-maker/BMI-Calculator-iOS13/blob/master/BMI%20Calculator/CalculateViewController.swift#L46

以下の理由で、

* メソッド内の前提条件はguardを使って早期returnすると、メソッド全体を囲うifのブロックをなくせるので、コードがシンプルになる
* クラッシュの原因になるため強制アンラップは極力行わない

このように書くとSwiftらしい書き方になります。

```
     guard segue.identifier == "goToResult", let destinationVC = segue.destination as? ResultsViewController else { return }            
```

**Comment by aikms-maker** [comment]
@inushima 
PR立てましたのでかくにんお願いいたします！
https://github.com/aikms-maker/BMI-Calculator-iOS13/pull/2

**Comment by aikms-maker** [comment]
対応完了したのでクローズします。
